window.esdocSearchIndex = [
  [
    "shopify-api-flux/lib/utilities/apiproxy.js~apiproxy",
    "function/index.html#static-function-APIProxy",
    "<span>APIProxy</span> <span class=\"search-result-import-path\">shopify-api-flux/lib/utilities/APIProxy.js</span>",
    "function"
  ],
  [
    "shopify-api-flux/lib/resources/base.js~base",
    "class/lib/resources/Base.js~Base.html",
    "<span>Base</span> <span class=\"search-result-import-path\">shopify-api-flux/lib/resources/Base.js</span>",
    "class"
  ],
  [
    "shopify-api-flux/lib/stores/base.js~base",
    "class/lib/stores/Base.js~Base.html",
    "<span>Base</span> <span class=\"search-result-import-path\">shopify-api-flux/lib/stores/Base.js</span>",
    "class"
  ],
  [
    "shopify-api-flux/lib/resources/order.js~order",
    "class/lib/resources/Order.js~Order.html",
    "<span>Order</span> <span class=\"search-result-import-path\">shopify-api-flux/lib/resources/Order.js</span>",
    "class"
  ],
  [
    "shopify-api-flux/lib/stores/orders.js~orders",
    "class/lib/stores/Orders.js~Orders.html",
    "<span>Orders</span> <span class=\"search-result-import-path\">shopify-api-flux/lib/stores/Orders.js</span>",
    "class"
  ],
  [
    "shopify-api-flux/lib/resources/product.js~product",
    "class/lib/resources/Product.js~Product.html",
    "<span>Product</span> <span class=\"search-result-import-path\">shopify-api-flux/lib/resources/Product.js</span>",
    "class"
  ],
  [
    "shopify-api-flux/lib/stores/products.js~products",
    "class/lib/stores/Products.js~Products.html",
    "<span>Products</span> <span class=\"search-result-import-path\">shopify-api-flux/lib/stores/Products.js</span>",
    "class"
  ],
  [
    "shopify-api-flux/lib/resources/session.js~session",
    "class/lib/resources/Session.js~Session.html",
    "<span>Session</span> <span class=\"search-result-import-path\">shopify-api-flux/lib/resources/Session.js</span>",
    "class"
  ],
  [
    "shopify-api-flux/lib/stores/sessions.js~sessions",
    "class/lib/stores/Sessions.js~Sessions.html",
    "<span>Sessions</span> <span class=\"search-result-import-path\">shopify-api-flux/lib/stores/Sessions.js</span>",
    "class"
  ],
  [
    "shopify-api-flux/lib/resources/shop.js~shop",
    "class/lib/resources/Shop.js~Shop.html",
    "<span>Shop</span> <span class=\"search-result-import-path\">shopify-api-flux/lib/resources/Shop.js</span>",
    "class"
  ],
  [
    "shopify-api-flux/lib/stores/shops.js~shops",
    "class/lib/stores/Shops.js~Shops.html",
    "<span>Shops</span> <span class=\"search-result-import-path\">shopify-api-flux/lib/stores/Shops.js</span>",
    "class"
  ],
  [
    "shopify-api-flux/lib/utilities/webapi.js~webapi",
    "class/lib/utilities/WebAPI.js~WebAPI.html",
    "<span>WebAPI</span> <span class=\"search-result-import-path\">shopify-api-flux/lib/utilities/WebAPI.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "lib/constants.js",
    "file/lib/Constants.js.html",
    "lib/Constants.js",
    "file"
  ],
  [
    "lib/shopifyapi.js",
    "file/lib/ShopifyAPI.js.html",
    "lib/ShopifyAPI.js",
    "file"
  ],
  [
    "lib/__mocks__/whatwg-fetch.js",
    "file/lib/__mocks__/whatwg-fetch.js.html",
    "lib/__mocks__/whatwg-fetch.js",
    "file"
  ],
  [
    "lib/__tests__/shopifyapitest.js",
    "file/lib/__tests__/ShopifyAPITest.js.html",
    "lib/__tests__/ShopifyAPITest.js",
    "file"
  ],
  [
    "lib/dispatcher/apidispatcher.js",
    "file/lib/dispatcher/APIDispatcher.js.html",
    "lib/dispatcher/APIDispatcher.js",
    "file"
  ],
  [
    "lib/dispatcher/__tests__/apidispatchertest.js",
    "file/lib/dispatcher/__tests__/APIDispatcherTest.js.html",
    "lib/dispatcher/__tests__/APIDispatcherTest.js",
    "file"
  ],
  [
    "lib/resources/base.js",
    "file/lib/resources/Base.js.html",
    "lib/resources/Base.js",
    "file"
  ],
  [
    "lib/resources/base.js~base#clear",
    "class/lib/resources/Base.js~Base.html#instance-method-clear",
    "lib/resources/Base.js~Base#clear",
    "method"
  ],
  [
    "lib/resources/base.js~base#constructor",
    "class/lib/resources/Base.js~Base.html#instance-constructor-constructor",
    "lib/resources/Base.js~Base#constructor",
    "method"
  ],
  [
    "lib/resources/base.js~base#fetch",
    "class/lib/resources/Base.js~Base.html#instance-method-fetch",
    "lib/resources/Base.js~Base#fetch",
    "method"
  ],
  [
    "lib/resources/base.js~base#urlfor",
    "class/lib/resources/Base.js~Base.html#instance-method-urlFor",
    "lib/resources/Base.js~Base#urlFor",
    "method"
  ],
  [
    "lib/resources/base.js~base.apimethods",
    "class/lib/resources/Base.js~Base.html#static-get-apiMethods",
    "lib/resources/Base.js~Base.apiMethods",
    "member"
  ],
  [
    "lib/resources/order.js",
    "file/lib/resources/Order.js.html",
    "lib/resources/Order.js",
    "file"
  ],
  [
    "lib/resources/order.js~order#constructor",
    "class/lib/resources/Order.js~Order.html#instance-constructor-constructor",
    "lib/resources/Order.js~Order#constructor",
    "method"
  ],
  [
    "lib/resources/order.js~order#fetchallsince",
    "class/lib/resources/Order.js~Order.html#instance-method-fetchAllSince",
    "lib/resources/Order.js~Order#fetchAllSince",
    "method"
  ],
  [
    "lib/resources/order.js~order#fetchauthorized",
    "class/lib/resources/Order.js~Order.html#instance-method-fetchAuthorized",
    "lib/resources/Order.js~Order#fetchAuthorized",
    "method"
  ],
  [
    "lib/resources/order.js~order.apimethods",
    "class/lib/resources/Order.js~Order.html#static-get-apiMethods",
    "lib/resources/Order.js~Order.apiMethods",
    "member"
  ],
  [
    "lib/resources/product.js",
    "file/lib/resources/Product.js.html",
    "lib/resources/Product.js",
    "file"
  ],
  [
    "lib/resources/product.js~product#constructor",
    "class/lib/resources/Product.js~Product.html#instance-constructor-constructor",
    "lib/resources/Product.js~Product#constructor",
    "method"
  ],
  [
    "lib/resources/product.js~product#fetchallsince",
    "class/lib/resources/Product.js~Product.html#instance-method-fetchAllSince",
    "lib/resources/Product.js~Product#fetchAllSince",
    "method"
  ],
  [
    "lib/resources/product.js~product#fetchbycollection",
    "class/lib/resources/Product.js~Product.html#instance-method-fetchByCollection",
    "lib/resources/Product.js~Product#fetchByCollection",
    "method"
  ],
  [
    "lib/resources/product.js~product.apimethods",
    "class/lib/resources/Product.js~Product.html#static-get-apiMethods",
    "lib/resources/Product.js~Product.apiMethods",
    "member"
  ],
  [
    "lib/resources/session.js",
    "file/lib/resources/Session.js.html",
    "lib/resources/Session.js",
    "file"
  ],
  [
    "lib/resources/session.js~session#constructor",
    "class/lib/resources/Session.js~Session.html#instance-constructor-constructor",
    "lib/resources/Session.js~Session#constructor",
    "method"
  ],
  [
    "lib/resources/session.js~session#init",
    "class/lib/resources/Session.js~Session.html#instance-method-init",
    "lib/resources/Session.js~Session#init",
    "method"
  ],
  [
    "lib/resources/session.js~session.apimethods",
    "class/lib/resources/Session.js~Session.html#static-get-apiMethods",
    "lib/resources/Session.js~Session.apiMethods",
    "member"
  ],
  [
    "lib/resources/shop.js",
    "file/lib/resources/Shop.js.html",
    "lib/resources/Shop.js",
    "file"
  ],
  [
    "lib/resources/shop.js~shop#constructor",
    "class/lib/resources/Shop.js~Shop.html#instance-constructor-constructor",
    "lib/resources/Shop.js~Shop#constructor",
    "method"
  ],
  [
    "lib/resources/__tests__/basetest.js",
    "file/lib/resources/__tests__/BaseTest.js.html",
    "lib/resources/__tests__/BaseTest.js",
    "file"
  ],
  [
    "lib/resources/__tests__/ordertest.js",
    "file/lib/resources/__tests__/OrderTest.js.html",
    "lib/resources/__tests__/OrderTest.js",
    "file"
  ],
  [
    "lib/resources/__tests__/producttest.js",
    "file/lib/resources/__tests__/ProductTest.js.html",
    "lib/resources/__tests__/ProductTest.js",
    "file"
  ],
  [
    "lib/resources/__tests__/sessiontest.js",
    "file/lib/resources/__tests__/SessionTest.js.html",
    "lib/resources/__tests__/SessionTest.js",
    "file"
  ],
  [
    "lib/resources/__tests__/shoptest.js",
    "file/lib/resources/__tests__/ShopTest.js.html",
    "lib/resources/__tests__/ShopTest.js",
    "file"
  ],
  [
    "lib/stores/base.js",
    "file/lib/stores/Base.js.html",
    "lib/stores/Base.js",
    "file"
  ],
  [
    "lib/stores/base.js~base#areequal",
    "class/lib/stores/Base.js~Base.html#instance-method-areEqual",
    "lib/stores/Base.js~Base#areEqual",
    "method"
  ],
  [
    "lib/stores/base.js~base#constructor",
    "class/lib/stores/Base.js~Base.html#instance-constructor-constructor",
    "lib/stores/Base.js~Base#constructor",
    "method"
  ],
  [
    "lib/stores/base.js~base#reduce",
    "class/lib/stores/Base.js~Base.html#instance-method-reduce",
    "lib/stores/Base.js~Base#reduce",
    "method"
  ],
  [
    "lib/stores/base.js~base#where",
    "class/lib/stores/Base.js~Base.html#instance-method-where",
    "lib/stores/Base.js~Base#where",
    "method"
  ],
  [
    "lib/stores/orders.js",
    "file/lib/stores/Orders.js.html",
    "lib/stores/Orders.js",
    "file"
  ],
  [
    "lib/stores/orders.js~orders#constructor",
    "class/lib/stores/Orders.js~Orders.html#instance-constructor-constructor",
    "lib/stores/Orders.js~Orders#constructor",
    "method"
  ],
  [
    "lib/stores/products.js",
    "file/lib/stores/Products.js.html",
    "lib/stores/Products.js",
    "file"
  ],
  [
    "lib/stores/products.js~products#constructor",
    "class/lib/stores/Products.js~Products.html#instance-constructor-constructor",
    "lib/stores/Products.js~Products#constructor",
    "method"
  ],
  [
    "lib/stores/sessions.js",
    "file/lib/stores/Sessions.js.html",
    "lib/stores/Sessions.js",
    "file"
  ],
  [
    "lib/stores/sessions.js~sessions#getaccesstoken",
    "class/lib/stores/Sessions.js~Sessions.html#instance-method-getAccessToken",
    "lib/stores/Sessions.js~Sessions#getAccessToken",
    "method"
  ],
  [
    "lib/stores/sessions.js~sessions#getdomain",
    "class/lib/stores/Sessions.js~Sessions.html#instance-method-getDomain",
    "lib/stores/Sessions.js~Sessions#getDomain",
    "method"
  ],
  [
    "lib/stores/shops.js",
    "file/lib/stores/Shops.js.html",
    "lib/stores/Shops.js",
    "file"
  ],
  [
    "lib/stores/shops.js~shops#getcurrent",
    "class/lib/stores/Shops.js~Shops.html#instance-method-getCurrent",
    "lib/stores/Shops.js~Shops#getCurrent",
    "method"
  ],
  [
    "lib/stores/__tests__/basetest.js",
    "file/lib/stores/__tests__/BaseTest.js.html",
    "lib/stores/__tests__/BaseTest.js",
    "file"
  ],
  [
    "lib/stores/__tests__/orderstest.js",
    "file/lib/stores/__tests__/OrdersTest.js.html",
    "lib/stores/__tests__/OrdersTest.js",
    "file"
  ],
  [
    "lib/stores/__tests__/productstest.js",
    "file/lib/stores/__tests__/ProductsTest.js.html",
    "lib/stores/__tests__/ProductsTest.js",
    "file"
  ],
  [
    "lib/stores/__tests__/sessionstest.js",
    "file/lib/stores/__tests__/SessionsTest.js.html",
    "lib/stores/__tests__/SessionsTest.js",
    "file"
  ],
  [
    "lib/stores/__tests__/shopstest.js",
    "file/lib/stores/__tests__/ShopsTest.js.html",
    "lib/stores/__tests__/ShopsTest.js",
    "file"
  ],
  [
    "lib/utilities/apiproxy.js",
    "file/lib/utilities/APIProxy.js.html",
    "lib/utilities/APIProxy.js",
    "file"
  ],
  [
    "lib/utilities/urlhelpers.js",
    "file/lib/utilities/URLHelpers.js.html",
    "lib/utilities/URLHelpers.js",
    "file"
  ],
  [
    "lib/utilities/webapi.js",
    "file/lib/utilities/WebAPI.js.html",
    "lib/utilities/WebAPI.js",
    "file"
  ],
  [
    "lib/utilities/webapi.js~failedrequestcallback",
    "typedef/index.html#static-typedef-FailedRequestCallback",
    "lib/utilities/WebAPI.js~FailedRequestCallback",
    "typedef"
  ],
  [
    "lib/utilities/webapi.js~requestpromise",
    "typedef/index.html#static-typedef-RequestPromise",
    "lib/utilities/WebAPI.js~RequestPromise",
    "typedef"
  ],
  [
    "lib/utilities/webapi.js~successfulrequestcallback",
    "typedef/index.html#static-typedef-SuccessfulRequestCallback",
    "lib/utilities/WebAPI.js~SuccessfulRequestCallback",
    "typedef"
  ],
  [
    "lib/utilities/webapi.js~webapi#get",
    "class/lib/utilities/WebAPI.js~WebAPI.html#instance-method-get",
    "lib/utilities/WebAPI.js~WebAPI#get",
    "method"
  ],
  [
    "lib/utilities/__tests__/apiproxytest.js",
    "file/lib/utilities/__tests__/APIProxyTest.js.html",
    "lib/utilities/__tests__/APIProxyTest.js",
    "file"
  ],
  [
    "lib/utilities/__tests__/urlhelperstest.js",
    "file/lib/utilities/__tests__/URLHelpersTest.js.html",
    "lib/utilities/__tests__/URLHelpersTest.js",
    "file"
  ],
  [
    "lib/utilities/__tests__/webapitest.js",
    "file/lib/utilities/__tests__/WebAPITest.js.html",
    "lib/utilities/__tests__/WebAPITest.js",
    "file"
  ]
]